language: php

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.25.3

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  
before_script:
  - cp .env.example .env
  - cp docker-compose.example.yml docker-compose.yml
  - docker-compose up -d --build
  - docker-compose exec app php artisan migrate

script:
  - docker-compose exec app ./vendor/bin/phpunit ./tests
